algoritmo "Print salteando linha junto com variáveis"

var x: caractere // Define da variável x e o seu tipo

inicio // Define a função Inicio

    x <- "teste" // Atribuiu á variável X o texto "teste"

    escreval("Olá Mundo!")
    escreval(x, "ok")           // Escreve: teste ok (e depois pula linha)
    escreval(x, " ok")          // Escreve: teste  ok (e depois pula linha)
    escreva(x + " ok")          // Escreve: teste ok (e depois pula linha)

fimalgoritmo